version: '3.7'

services:
  node_app:
    build: ./
    #May or may not be needed
    # command: sh -c "sleep 10s"; npm start
    ports:
      - "2000:2000"
    tty: true
    depends_on:
      - postgres_sql


  postgres_sql:
    image: postgres:latest
    restart: always
    container_name: some-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=data_entry_systems