version: '3.7'

services:
  node_app:
    image: data-entry-system-doc
    restart: always
    #May or may not be needed
    # command: sh -c "sleep 10s"; npm start
    ports:
      - "4000:2000"
    network_mode: "host"
    hostname: localhost
    depends_on:
      - postgres_sql


  postgres_sql:
    image: postgres:latest
    container_name: alpine-postgres
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=data_entry_systems
    volumes: 
      - ~/dbdata:/var/lib/postgresql/data